export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const UPDATING_START = 'UPDATING_START';
export const UPDATING_SUCCESS = 'UPDATING_SUCCESS';
export const UPDATING_FAIL = 'UPDATING_FAIL';

export const LOG_OUT = 'LOG_OUT';

export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const FOLLOWERS_UPDATED = 'FOLLOWERS_UPDATED';
export const FOLLOWING_UPDATED = 'FOLLOWING_UPDATED';

export const UPLOAD_START = 'UPLOAD_START';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAIL = 'UPLOAD_FAIL';

export const RETRIEVING_START = 'RETRIEVING_START';
export const RETRIEVING_SUCCESS = 'RETRIEVING_SUCCESS';
export const RETRIEVING_FAIL = 'RETRIEVING_FAIL';

export const POST_COMMENTED = 'POST_COMMENTED';
export const POST_LIKES_UPDATED = 'POST_LIKES_UPDATED';
export const POST_UPDATED = 'POST_UPDATED';
export const POST_DELETED = 'POST_DELETED';
export const POSTS_PAGE_REQUEST = 'POSTS_PAGE_REQUEST';
export const POSTS_PAGE_SUCCESS = 'POSTS_PAGE_SUCCESS';
export const POSTS_PAGE_FAILURE = 'POSTS_PAGE_FAILURE';

export const SAVE_USER = 'SAVE_USER';

export const SET_THEME = 'SET_THEME';
export const TOGGLE_THEME = 'TOGGLE_THEME';

export const NOTIFICATIONS_FETCH_START = 'NOTIFICATIONS_FETCH_START';
export const NOTIFICATIONS_FETCH_SUCCESS = 'NOTIFICATIONS_FETCH_SUCCESS';
export const NOTIFICATIONS_FETCH_FAIL = 'NOTIFICATIONS_FETCH_FAIL';
export const NOTIFICATION_RECEIVED = 'NOTIFICATION_RECEIVED';
export const NOTIFICATION_MARKED_READ = 'NOTIFICATION_MARKED_READ';
export const NOTIFICATIONS_MARKED_ALL_READ = 'NOTIFICATIONS_MARKED_ALL_READ';

